[Interface]
# Key for warszawa1_protonvpn
# Bouncing = 15
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 4IVP6EHnaL0xLtl5MUXzdexsEV172n7wJuvSowipemY=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# PL#88
PublicKey = wpfRQRhJirL++QclFH6SDhc+TuJJB4UxbCABy7A1tS4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.186.193:51820

PersistentKeepalive = 25